package com.mcb.billing.customer.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;

/**
 * Customer master data of the billing platform (JPA entity -> table {@code customers}).
 *
 * <p>Kept as a flat entity (no embedded value objects) on purpose for the first version.
 * The billing address lives as plain columns; it can be extracted into an {@code @Embeddable}
 * later without changing the API.
 */
@Entity
@Table(
        name = "customers",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_customers_customer_number", columnNames = "customer_number"),
                @UniqueConstraint(name = "uk_customers_email", columnNames = "email")
        }
)
public class Customer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Business key, generated by the service (not provided by the client). */
    @NotBlank
    @Size(max = 50)
    @Column(name = "customer_number", nullable = false, unique = true, length = 50)
    private String customerNumber;

    @NotBlank
    @Size(max = 200)
    @Column(name = "company_name", nullable = false, length = 200)
    private String companyName;

    /** Optional contact person at the company. */
    @Size(max = 200)
    @Column(name = "contact_person", length = 200)
    private String contactPerson;

    /** Required: the notification-service reaches the customer only via email. */
    @NotBlank
    @Email
    @Size(max = 255)
    @Column(nullable = false, unique = true, length = 255)
    private String email;

    @Size(max = 50)
    @Column(length = 50)
    private String phone;

    // --- Billing address as flat columns (no @Embedded, per decision) ---

    @Size(max = 200)
    @Column(length = 200)
    private String street;

    @Size(max = 20)
    @Column(name = "postal_code", length = 20)
    private String postalCode;

    @Size(max = 100)
    @Column(length = 100)
    private String city;

    @Size(max = 100)
    @Column(length = 100)
    private String country;

    /** VAT identification number (relevant for B2B/EU invoicing). */
    @Size(max = 30)
    @Column(name = "vat_id", length = 30)
    private String vatId;

    /** Soft-delete flag; new customers are active by default. */
    @Column(nullable = false)
    private boolean active = true;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-args constructor required by JPA/Hibernate. */
    protected Customer() {
    }

    /**
     * Creates a new customer from the mandatory client-provided fields.
     * The {@code customerNumber} is assigned separately by the service before saving;
     * optional fields (address, phone, ...) are set via their setters.
     */
    public Customer(String companyName, String email) {
        this.companyName = companyName;
        this.email = email;
        this.active = true;
    }

    //  Getters + setters
    // id, createdAt, updatedAt are managed by JPA/Hibernate -> getters only.

    public Long getId() {
        return id;
    }

    public String getCustomerNumber() {
        return customerNumber;
    }

    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getContactPerson() {
        return contactPerson;
    }

    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getVatId() {
        return vatId;
    }

    public void setVatId(String vatId) {
        this.vatId = vatId;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
