package com.mcb.billing.invoice.domain;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import com.mcb.billing.invoice.exception.InvalidInvoiceStateException;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * An invoice and its line items (aggregate root). Line items are owned by the
 * invoice (cascade + orphanRemoval), and the total is kept in sync with them.
 *
 * <p>{@code customerNumber} is a soft reference to a customer in the customer-service
 * (validated via Feign on creation) - there is no cross-service foreign key.
 */
@Entity
@Table(
        name = "invoices",
        uniqueConstraints = @UniqueConstraint(name = "uk_invoices_invoice_number", columnNames = "invoice_number")
)
public class Invoice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Business key, generated by the service (e.g. INV-00001). */
    @NotBlank
    @Size(max = 50)
    @Column(name = "invoice_number", nullable = false, unique = true, length = 50)
    private String invoiceNumber;

    /** Soft reference to the customer's business key (no cross-service FK). */
    @NotBlank
    @Size(max = 50)
    @Column(name = "customer_number", nullable = false, length = 50)
    private String customerNumber;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private InvoiceStatus status = InvoiceStatus.DRAFT;

    @NotBlank
    @Size(max = 3)
    @Column(nullable = false, length = 3)
    private String currency = "EUR";

    @NotNull
    @PositiveOrZero
    @Column(name = "total_amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal totalAmount = BigDecimal.ZERO;

    /** Set when the invoice is issued (null while DRAFT). */
    @Column(name = "issue_date")
    private LocalDate issueDate;

    @Column(name = "due_date")
    private LocalDate dueDate;

    @OneToMany(mappedBy = "invoice", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<InvoiceItem> items = new ArrayList<>();

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-args constructor required by JPA/Hibernate. */
    protected Invoice() {
    }

    /** Creates a new DRAFT invoice for a customer. The customerNumber is expected
     *  to be validated (via the customer-service) before this is called. */
    public Invoice(String customerNumber, String currency, LocalDate dueDate) {
        this.customerNumber = customerNumber;
        this.currency = currency;
        this.dueDate = dueDate;
        this.status = InvoiceStatus.DRAFT;
    }

    /** Adds a line item, keeps both sides of the association in sync and updates the total. */
    public void addItem(InvoiceItem item) {
        items.add(item);
        item.setInvoice(this);
        recalculateTotal();
    }

    /** Recomputes the total from the current line items. */
    public void recalculateTotal() {
        this.totalAmount = items.stream()
                .map(InvoiceItem::getLineTotal)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    /** Transitions DRAFT -> ISSUED and stamps the issue date. Rich-domain behavior:
     *  the invariant lives on the aggregate, not in a service. */
    public void issue() {
        if (status != InvoiceStatus.DRAFT) {
            throw new InvalidInvoiceStateException("Only a DRAFT invoice can be issued (was " + status + ")");
        }
        this.status = InvoiceStatus.ISSUED;
        this.issueDate = LocalDate.now();
    }

    // --- Getters (id/timestamps/status/total managed internally -> read only) ---

    public Long getId() {
        return id;
    }

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public String getCustomerNumber() {
        return customerNumber;
    }

    public InvoiceStatus getStatus() {
        return status;
    }

    public String getCurrency() {
        return currency;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public LocalDate getIssueDate() {
        return issueDate;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    /** Unmodifiable view - items are added via {@link #addItem(InvoiceItem)}. */
    public List<InvoiceItem> getItems() {
        return Collections.unmodifiableList(items);
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
