-- Initial schema for the customer-service (PostgreSQL).
-- Owned by Flyway; Hibernate runs with ddl-auto=validate against it.

CREATE TABLE customers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number VARCHAR(50)  NOT NULL,
    company_name    VARCHAR(200) NOT NULL,
    contact_person  VARCHAR(200),
    email           VARCHAR(255) NOT NULL,
    phone           VARCHAR(50),
    street          VARCHAR(200),
    postal_code     VARCHAR(20),
    city            VARCHAR(100),
    country         VARCHAR(100),
    vat_id          VARCHAR(30),
    active          BOOLEAN      NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_customers_customer_number UNIQUE (customer_number),
    CONSTRAINT uk_customers_email UNIQUE (email)
);

-- Sequence backing the human-readable customer number (C-00001, C-00002, ...).
CREATE SEQUENCE customer_number_seq START WITH 1 INCREMENT BY 1;
