-- Initial schema for the notification-service (PostgreSQL).
-- Owned by Flyway; Hibernate runs with ddl-auto=validate against it.

CREATE TABLE notification_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        VARCHAR(100)  NOT NULL,
    event_type      VARCHAR(50)   NOT NULL,
    invoice_number  VARCHAR(50)   NOT NULL,
    customer_number VARCHAR(50)   NOT NULL,
    channel         VARCHAR(20)   NOT NULL,
    message         VARCHAR(500)  NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- Idempotent-consumer guard: an event is recorded at most once.
    CONSTRAINT uk_notification_log_event_id UNIQUE (event_id)
);
