-- Initial schema for the invoice-service (PostgreSQL).
-- Owned by Flyway; Hibernate runs with ddl-auto=validate against it.

CREATE TABLE invoices (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number  VARCHAR(50)   NOT NULL,
    customer_number VARCHAR(50)   NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    currency        VARCHAR(3)    NOT NULL,
    total_amount    NUMERIC(12, 2) NOT NULL,
    issue_date      DATE,
    due_date        DATE,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_invoices_invoice_number UNIQUE (invoice_number)
);

CREATE TABLE invoice_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT        NOT NULL,
    description VARCHAR(300)  NOT NULL,
    quantity    INTEGER       NOT NULL,
    unit_price  NUMERIC(12, 2) NOT NULL,
    line_total  NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id)
);

-- Sequence backing the human-readable invoice number (INV-00001, INV-00002, ...).
CREATE SEQUENCE invoice_number_seq START WITH 1 INCREMENT BY 1;
